_format_version: "3.0"

services:
  # ✅ API C# Producer
  - name: csharp-api-service
    url: http://csharp-producer:8080
    routes:
      - name: api-route
        paths:
          - /api/v1
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS

  # ✅ Frontend React
  - name: frontend-service
    url: http://sentinel-front:3000
    routes:
      - name: frontend-route
        paths:
          - /
        strip_path: false
        methods:
          - GET